# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EcoModel
                                 A QGIS plugin
 Plugin to model economic consequences of climate changes
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-07-23
        copyright            : (C) 2021 by Bo Victor Thomsen - AestasGIS Denmark
        email                : bvt@aestas.dk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load EcoModel class from file EcoModel.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .eco_model import EcoModel
    return EcoModel(iface)
